---
# tasks file for ansible-nginx

- include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Install Nginx
  package:
    name: nginx
    state: present

- name: Copy config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
