---
- name: Ensure config directory
  file:
    path: "{{ nginx_conf_dir }}"
    state: directory
    owner: "{{ nginx_conf_dir_user }}"
    group: "{{ nginx_conf_dir_group }}"
    mode: "{{ nginx_conf_dir_mode }}"

- name: Ensure log directory
  file:
    path: "{{ nginx_log_dir }}"
    state: directory
    owner: "{{ nginx_log_dir_user }}"
    group: "{{ nginx_log_dir_group }}"
    mode: "{{ nginx_log_dir_mode }}"
