---
- name: Create config directories
  file:
    path: "{{ nginx_conf_dir }}/{{ item }}"
    state: directory
    owner: "{{ nginx_conf_dir_user }}"
    group: "{{ nginx_conf_dir_group }}"
    mode: "{{ nginx_conf_dir_mode }}"
  with_items:
    - "sites-available"
    - "sites-enabled"
    - "conf.d"

- name: Create log directory
  file:
    path: "{{ nginx_log_dir }}"
    state: directory
    owner: "{{ nginx_log_dir_user }}"
    group: "{{ nginx_log_dir_group }}"
    mode: "{{ nginx_log_dir_mode }}"
