---
- name: Add APT signing key
  apt_key:
    id: 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
    keyserver: ha.pool.sks-keyservers.net

- name: Add Nginx repository
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - deb https://nginx.org/packages/mainline/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx
    - deb-src https://nginx.org/packages/mainline/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx
